### ISSUE TITLE
Python implementation checklist

### ISSUE THREAD

**Issue by naggie** [naggie/sd01#13]
Use this issue template to integrate a new language.

- [x] Announcer
  - [ ] Start() method (should be idempotent)
  - [ ] Stop() method (should be idempotent)
  - [x] Announcement at 5 second interval
  - [ ] Command line client (args: <service name> <port>)

- [x] Discoverer
  - [ ] Start() method (should be idempotent)
  - [x] Get services method (wait parameter, a bool to block for the interval period)
  - [ ] Stop() method (should be idempotent)
  - [x] Timeout at 10 second interval (service appears offline)
  - [ ] Number of known services GC (limit to 1000)
  - [ ] Command line client (args: <service name>)

- [x] Validation
  - [x] Port range
  - [x] Service name length
  - [x] Service name character set (ASCII)

- [x] Tests
  - [x] Announce/Discover/Timeout
  - [x] Invalid port
  - [x] Invalid character set on service name
  - [x] Service name too long
  - [x] Foreign protocol rejection (banana)
  - [x] Foreign service rejection (bar)
  - [x] Start/stop idempotency test for Announcer
  - [ ] Start/stop idempotency test for Discoverer
